### ISSUE TITLE
can't find the files under sherlock2.0

### ISSUE THREAD

**Issue by hhongli** [singularityhub/sbgrid-singularity#1] opened 2017-10-31 17:50 UTC
The singularity works under our sherlock1 system. However if we login to sherlock2.0, we can find the folder /oak and /scratch, but no file under these two folder.

**Comment by alburse** [comment] 2017-10-31 17:57
I also tested this and got the same problem as Hongli.

**Comment by vsoch** [comment] 2017-10-31 19:07
okay so you are just missing the path to the image itself? Not the software? @preese has there been any change to the location of the image file?

**Comment by vsoch** [comment] 2017-10-31 19:12
The docs might not be up to date with where the final resting place of the container turned out to be. From @preese email:

>> A new version of the Relion Singularity container is ready for you to try out. It was loaded into Yiorgo's OAK space, as sbgrid_stanford-skiniotis--relion_20171026.img Vanessa updated the docs for how to use: https://github.com/singularityhub/sbgrid-singularity/tree/master/relion This has all the versions of Relion that the SBgrid distribution has.  Vanessa's docs list all of the other tools loaded.

Are you looking in "Yiorgio's Oak Space?"

**Comment by preese** [comment] 2017-10-31 22:11
Hi,

First, and sorry to add a level of complexity, for these type of 
permission problems, it is better to send reports to the standard 
address, research-computing-support@stanford.edu.

If you have problems with the Singularity image itself, then the github 
process is the way to go to report problems.

Second, be sure everyone is using the correct path to the Singularity image:
/oak/stanford/groups/yiorgo/lana/Yan/sbgrid_stanford-skiniotis--relion_20171026.img

If the full path doesn't solve the problem, then it is likely that the 
user isn't in Yiorogo's group and therefore can't go through the main 
directory to get to the image.  Yiorgo can send a note to 
research-computing-support@stanford.edu  requesting that a student be 
added to his group and that should solve that issue.

Phil

**Comment by hhongli** [comment] 2017-10-31 22:15
We can find the omg file in 
-rwxrwxrwx+ 1 xtyzhang yiorgo 13G Oct 30 17:25 /oak/stanford/groups/yiorgo/sbgrid_stanford-skiniotis--relion_20171026.img

Our problem is in sherlock2.0, after we get in the container, we will be under the folder /oak
and it's empty. We can't see any files under /oak. The same with folder /scratch.

**Comment by preese** [comment] 2017-10-31 22:54
We can find the img file in:
-rwxrwxrwx+ 1 xtyzhang yiorgo 13G Oct 30 17:25 /oak/stanford/groups/yiorgo/sbgrid_stanford-skiniotis--relion_20171026.img

Our problem is in sherlock2.0, after we get in the container, we will be under the folder /oak
and it's empty. We can't see any files under /oak. The same happens with folder /scratch.
In sherlock1, we do not have this issue. 

Hongli


On 10/31/17, 3:11 PM, "Phil Reese" <preese@stanford.edu> wrote:

    Hi,
    
    First, and sorry to add a level of complexity, for these type of 
    permission problems, it is better to send reports to the standard 
    address, research-computing-support@stanford.edu.
    
    If you have problems with the Singularity image itself, then the github 
    process is the way to go to report problems.
    
    Second, be sure everyone is using the correct path to the Singularity image:
    /oak/stanford/groups/yiorgo/lana/Yan/sbgrid_stanford-skiniotis--relion_20171026.img
    
    If the full path doesn't solve the problem, then it is likely that the 
    user isn't in Yiorogo's group and therefore can't go through the main 
    directory to get to the image.  Yiorgo can send a note to 
    research-computing-support@stanford.edu  requesting that a student be 
    added to his group and that should solve that issue.
    
    Phil

**Comment by vsoch** [comment] 2017-10-31 23:12
It looks like Phil's message got a little tangled in the reply from the email - I'll highlight in case you didn't see:

>> If the full path doesn't solve the problem, then it is likely that the
    user isn't in Yiorogo's group and therefore can't go through the main
    directory to get to the image.  Yiorgo can send a note to
    research-computing-support@stanford.edu  requesting that a student be
    added to his group and that should solve that issue.

**Comment by alburse** [comment] 2017-11-01 20:42
Phil mentioned the path as 
/oak/stanford/groups/yiorgo/lana/Yan/sbgrid_stanford-skiniotis--relion_20171026.img.
This path is under Yan's folder so Yan only can see it. 
We found this image also under 
/oak/stanford/groups/yiorgo/sbgrid_stanford-skiniotis--relion_20171026.img
I believe the problem is not about the person not being in Yiorgo's group, since I and Hongli are in Yiorgo's group and we cannot reach the files under /oak when we use Sherlock2 only after getting into singularity. We can reach the files under /oak when we are on Sherlock1 and we get into singularity. Basically, somehow the files do not show up when we use singularity in Sherlock2 but not in Sherlock1.

**Comment by vsoch** [comment] 2017-11-01 20:47
I'm not sure I can be of much help here - I think Phil will see the email and be able to respond. Thanks for your patience and sorry for the trouble!

**Comment by vsoch** [comment] 2017-11-02 18:27
hey @alburse @hhongli ! We had to fuss around with a few config settings, but you should be able to see /oak and /scratch when you use singularity 2.4 on sherlock 2. Could you give it another try?

```
$ module load singularity/2.4
$ which singularity
/share/software/user/open/singularity/2.4/bin/singularity
$ singularity --version
2.4-dist

$ singularity shell vsoch-hello-world-master.img 
Singularity: Invoking an interactive shell within container...

Singularity vsoch-hello-world-master.img:~> ls /
bin   etc   lib64	media  net  proc     run      share	   sys	var
boot  home  lost+found	misc   oak  rawr.sh  sbin     singularity  tmp
dev   lib   lscratch	mnt    opt  root     scratch  srv	   usr
```
we have scratch and oak!

**Comment by alburse** [comment] 2017-11-02 21:02
Hi @vsoch 
Yes, I can see the files and folders under /oak and /scratch. Thanks

**Comment by vsoch** [comment] 2017-11-02 21:28
Great! Closing  issue.

**Closed as completed by vsoch** 2017-11-02 21:28 UTC
